import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Resume Enhancer',
  description: 'Terms of Service for Resume Enhancer.',
};

const termsSections = [
  {
    title: 'Acceptance of Terms',
    body: [
      'By accessing or using Resume Enhancer, you agree to be bound by these Terms of Service.',
      'If you do not agree to these terms, do not use the service.',
    ],
  },
  {
    title: 'Use of the Service',
    body: [
      'You may use the service only for lawful purposes and in accordance with these terms.',
      'You are responsible for all content submitted through your account or API configuration.',
    ],
  },
  {
    title: 'User Content',
    body: [
      'You retain ownership of your submitted content, including resumes and job descriptions.',
      'You grant us permission to process that content solely to operate and improve the service.',
    ],
  },
  {
    title: 'AI-Generated Output',
    body: [
      'Outputs generated by AI may be inaccurate, incomplete, or unsuitable for specific contexts.',
      'You are responsible for reviewing and validating generated content before relying on it.',
    ],
  },
  {
    title: 'Prohibited Conduct',
    body: [
      'You must not use the service to violate law, infringe rights, or submit malicious content.',
      'You must not attempt to disrupt, reverse engineer, or abuse platform security controls.',
    ],
  },
  {
    title: 'Disclaimers and Limitation of Liability',
    body: [
      'The service is provided on an "as is" and "as available" basis without warranties of any kind.',
      'To the fullest extent permitted by law, we are not liable for indirect or consequential damages arising from service use.',
    ],
  },
  {
    title: 'Changes and Termination',
    body: [
      'We may modify these terms or discontinue parts of the service at any time.',
      'Your continued use of the service after changes are posted constitutes acceptance of the revised terms.',
    ],
  },
] as const;

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#F0F0E8] text-[#000000]">
      <nav className="border-b-2 border-black bg-[#F0F0E8]">
        <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-4">
          <Link
            href="/dashboard"
            className="font-mono text-xs uppercase tracking-wider hover:underline"
          >
            Back to Dashboard
          </Link>
          <div className="flex items-center gap-4">
            <Link
              href="/privacy-policy"
              className="font-mono text-xs uppercase tracking-wider hover:underline"
            >
              Privacy
            </Link>
            <Link
              href="/terms-of-service"
              className="font-mono text-xs uppercase tracking-wider underline"
            >
              Terms
            </Link>
          </div>
        </div>
      </nav>

      <section className="mx-auto w-full max-w-5xl px-6 py-12 md:py-16">
        <h1 className="font-serif text-4xl font-bold tracking-tight md:text-5xl">
          Terms of Service
        </h1>
        <p className="mt-4 font-mono text-xs uppercase tracking-wider text-[#4B5563]">
          Last updated: March 5, 2026
        </p>
        <p className="mt-6 max-w-3xl font-sans text-base leading-relaxed">
          These terms govern your use of Resume Enhancer and outline rights, obligations, and
          limitations related to the platform.
        </p>

        <div className="mt-10 space-y-6">
          {termsSections.map((section) => (
            <article
              key={section.title}
              className="border-2 border-black bg-white p-6 shadow-[4px_4px_0px_0px_#000000]"
            >
              <h2 className="font-serif text-2xl font-semibold">{section.title}</h2>
              <div className="mt-4 space-y-3">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="font-sans text-sm leading-relaxed text-[#111111]">
                    {paragraph}
                  </p>
                ))}
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
